spin_manifest_version = 2

[application]
name = "magic-8-ball"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-magic8-ball"
component = "magic8-ball"
route = "/magic-8"

[[trigger.http]]
id = "trigger-fileserver"
component = "fileserver"
route = "/..."

[component.magic8-ball]
source = "target/wasm32-wasi/release/magic_8_ball.wasm"
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
ai_models = ["llama2-chat"]

[component.magic8-ball.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
files = [{ source = "assets", destination = "/" }]
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
